# All activation rounds need to be declared as strings containing valid uint64 numbers. All values will be checked in the
# enableRoundsHandler for correctness. The toml parser library can not correctly parse uint64, currently.

# Each activation round definition contains an optional slice of strings. These are useful, for example, when we have
# some exceptions to process in a different manner at a special round (say a block, a transaction, a smart contract result and such)

[RoundActivations]
    [RoundActivations.DisableAsyncCallV1]
        # just an example, not used for this flag
        Options = ["test string1", "test string 2"]
        Round = "18446744073709551614"
